#include "stdafx.h"
#include "CategoryMainForm.h"
#include "FilmMainForm.h"
#include "ActorMainForm.h"
#include "InsertMovieForm.h"
#include "UpdateMovieForm.h"
#include "InsertActorForm2.h"
#include "../FilmManager/Headers/Database Headers/ConnectionProperties.h"